---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgB5wCzujSz+wPxhnYIqNMfXtgUFk4fvlXTS/JcYasO277mwvH3zfHs5GFlhSNzIXQgP52e46NDv3AK3BLK2Wejb8NStolO/OulAiWOThmw0QD6gzk9kfH2TR9g2P89WKCaM5TbU6Fbfk5XeNHt0uu6p6MnT84ebgLptdpWodpbWQ+3x1i7alc2Xy5WC60Yx62f+NQZY8Re7hx/E9y7Pk/xgkINPhbEyYLr23Y+YVADIEp3onBTiIA3GeerpTqnf/p+tP0quQOyJpQCaTyIPwksb08big/Xl7DM28H4OoFYd9XmlzPyTgE/W8ISg0XfhW0IrUfGLwfgliE2JeItKtwaQs9EeNYGEQ0jN0zN1F2NfWhrMNh4rVQqskHdRvo7dTF85ANriOa1I0OpZknsTxQWGdrITdz8f8gpDOFkzUFtqUT20Yg3HcPChJZTq3V3gqw9HDQr3t8GW0Bf0Wk6wqZbrH877MhTc6Yj2C293OFtzndVOaCfu1nsgtCIeeS2DWxFbfxalg7aNny8fjLYF2OAND5ZG0Qr+CmqxZZqRuoG7xdtVCKbFf2xxCXo6C3ggLqo8+Quy3w06FOAr/3wY5/ZgrzW+JzcuSOrUucK20Ht2bRqbltrEVoCbxdYs8UGAVO8VV+cW2rE7aBl2hxOGRt/kp+Wr8hdCFAyqD+Hwey2OWX83W5UJOxqF3Z61rPETJFjH/OkUtA==
  template:
    metadata:
      name: database
      namespace: default
