---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-nodejs-microservice-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgDBrhY3hz7DR+v0nskdKbZnWsM3jdZ26PI/1Hr7Fu0zJzZQoBBc267UEN+IbYKbQAiL1rzt+yHMbKSjvuYdI60cOr1lfld0afQIjIrH4jkywM360sDYtXGy42lbHhcWjpJnNLqP5dpV2PQPQJsT97z+Hr2c6KWVIqBc4YZNkGwlZ0f+idwaUOZOiGMut69RjnCiOR/CXmh2Eou/Nzxf659ymGc/tcMhQwvKJF9IF0a92EB74Rr5sOOk/860N9lGpcK45XZB23NtdctTuY2PQS9bdT6G/+TzRwLWoINPtvb8e2zWkGucimkQDH1txeH/z6cNKsFfr0eILcn7XwkiJhSOEsvvzA7yi+DnTbDHeLcIrpbf3sSwiNB86ez40Bfueaj0MWSxdJ5HKiGFiuo0kfgm8zaskPZ8P9s3C9L+Q6dJMKrsAiFff2lZ6r3WemaXznRWJNjkj1IfnKacn5xDAMH27bHxrIT7tphdGOouG2GgD+lx0bkq/JRMMds3tgZJmCUBT6Vc4p190c/rc4lgLus9yIXDxqpbHBnh0N3NrKAuCFVnv9mduiDSUSx1DmbS9jtHRf8wo9EU5fN4ZnyId0MNOTiV2q00p1z0yTb/Qhzqk13lMC1xH74SX3mNQ/jAmbWyjUfmlW06nWn5FPF6YRai95G0i9Er/75EXEZsH4KgSUkNBUdy4OL0y38Xq55ARD+b2YEn7Q==
  template:
    metadata:
      name: my-nodejs-microservice-secret
      namespace: default
